[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/projects/*"
  to = "/portfolio/:splat"
  status = 301

[[redirects]]
  from = "/about"
  to = "/"
  status = 302

  from = "/*"
  to = "/404/index.html"
  status = 404
